language:
- python
python:
- '3.5'
- '2.7'
install:
- pip install -r requirements.txt
script:
- nosetests
deploy:
  provider: heroku
  api_key:
    secure: XU+mimoew/H36gDvE7AOw9k1Tc7jtue2+veuj478GiEe3TSdyfNF18OVjINjKIXj55eEcgttZvD7h6d5f40z1EwuB5DmnUNSL1H634ThtVGKrfz/xXDfN4MKRXzz85kujSEn7ZFAggwEMW9KegMV0yRM+ONd0OnGiz4pMj8r9wJ6Q6PvelQOB0OfQaXjRRjtPDsiIKAmuz3nGsJEB5+3slFlkC4sS6kqNkFKnRk+zlySRDeoRCbZq4QXuZtGDsSusr7KeHzQoJV2MuWE2iZ7D1aaMQ7BSaJ5qDBsMsBpxptdGfQ66fe1rdEzBhLt7eAvfZTCShJUFP4U9ijrPJDqwGyKKcOiLO/L9rb5NR+3i4myTlekhX6G7Pxk6mVGIdXyCuBZGynbhmNWQwunpsYWRX7PHxA9YLPduOYqJxjjcQhy0YGxP6bPgsLo/H6zqbTLpqc+wmH2qcflf7iA67FXYZf5bPcDQ6pn99PBQwn1m+yzTjEV+ywS+30H0nD+0J6Tu2gJeYTah9N0olIDsTiae6GunUWEk6MYS0gej8d5efLmVwcPHQGyOodSVVmIwHh13gJAhJV+DbwoHM6A8gWd6ohSz2y5NPd3zQg9K9emRNx3f+UJompPGilk+GWhONdCXZ17KeJ06IWIQZm396gulwKa175eouzmHxSTsO2xssM=
  app: dry-temple-15376
  on:
    branch: master
    python: '3.5'
    repo: topleft/flasktasker
